parameters:

services:
    userNotifier:
        class:     UserNotification\NullUserNotification

    userController:
        class:     Controller\UserController
        arguments: ['@userNotifier']